backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "actions"
    label: "Action"
    folder: "src/pages/action"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "action"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Date from", name: "dateFrom", widget: "date"}
      - {label: "Date to", name: "dateTo", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}

  - name: "projects"
    label: "Projects"
    folder: "src/pages/project"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "action"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Date from", name: "dateFrom", widget: "date"}
      - {label: "Date to", name: "dateFrom", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}

  - name: "members"
    label: "Members"
    folder: "src/pages/members"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "action"}
      - {label: "Full name", name: "name", widget: "string"}
      - {label: "Bio", name: "bio", widget: "markdown"}
      - {label: "Member from", name: "from", widget: "date"}
      - {label: "Member to", name: "to", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Location" , name: "location", widget: "string"}
      - {label: "Website" , name: "website", widget: "string"}
      - label: "Involved"
        name: "involved"
        widget: "relation"
        collection: "actions"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]

  - name: "creativeBoard"
    label: "Creative Board"
    folder: "src/pages/creative-board"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "action"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - label: "Event"
            name: "event"
            widget: "object"
            fields:
              - {label: "Event Name", name: "eventName", widget: "string"}
              - {label: "Event Date", name: "eventDate", widget: "date"}
              - {label: "Event Image", name: "eventImage", widget: "image"}
          - label: "Featured Project"
            name: "featuredProject"
            widget: "relation"
            collection: "projects"
            searchFields: ["title"]
            valueField: "title"
            displayFields: ["title"]

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Featured Action", name: "featuredAction", widget: "string"}
          - {label: "Details", name: "details", widget: "markdown"}