backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "actions"
    label: "Action"
    folder: "src/pages/action"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "action"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Date from", name: "dateFrom", widget: "date"}
      - {label: "Date to", name: "dateTo", widget: "date"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Izložba / Exhibition", "Radionica / Workshop", "Performans / Performance", "Razgovori / Conversations", "Koncert / Concert", "Šetnja / Walks", "Prezentacija / Presentation", "Akcija / Action", "Interakcija / Interaction", "Diskusija / Discussion", "Intervencija / Intervention", "Instalacija / Installation", "Anketa / Survey", "Web projekat / Web project", "Okrugli sto / Round table", "Hepening / Happening", "Online projekat / Online project", "konferencija / conference", "Foto-šetnja / Photo Walk", "Igra / Game"]}
      - label: "Tags"
        name: "tags"
        widget: "relations"
        limit: "300"
        collection: "actions"
        searchFields: ["tags"]
        valueField: "tags"
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
      - {label: "Video", name: "video", widget: "string"}
      - label: "Members"
        name: "members"
        widget: "relations"
        limit: "300"
        collection: "members"
        searchFields: ["name"]
        valueField: "name"
      - label: "Mentors"
        name: "mentors"
        widget: "relations"
        limit: "300"
        collection: "members"
        searchFields: ["name"]
        valueField: "name"
      - label: "Projects"
        name: "projects"
        widget: "relations"
        limit: "300"
        collection: "projects"
        searchFields: ["name"]
        valueField: "name"
      - label: "Module"
        name: "modules"
        widget: "relations"
        limit: "300"
        collection: "projects"
        searchFields: ["name"]
        valueField: "name"
      - label: "Collaborators"
        name: "collaborators"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "link", name: "link", widget: "string"}
      - label: "Partners"
        name: "partners"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
      - label: "Links"
        name: "links"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "link", name: "link", widget: "string"}

  - name: "projects"
    label: "Projects"
    folder: "src/pages/project"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Date from", name: "dateFrom", widget: "date"}
      - {label: "Date to", name: "dateTo", widget: "date"}
      - label: "Tags"
        name: "tags"
        widget: "relations"
        limit: "300"
        collection: "actions"
        searchFields: ["tags"]
        valueField: "tags"
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
      - {label: "Video", name: "video", widget: "string"}
      - label: "Members"
        name: "members"
        widget: "relations"
        limit: "300"
        collection: "members"
        searchFields: ["name"]
        valueField: "name"
      - label: "Mentors"
        name: "mentors"
        widget: "relations"
        limit: "300"
        collection: "members"
        searchFields: ["name"]
        valueField: "name"
      - label: "Partners"
        name: "partners"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "link", name: "link", widget: "string"}
      - label: "Links"
        name: "links"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "link", name: "link", widget: "string"}




  - name: "members"
    label: "Members"
    folder: "src/pages/member"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "member"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Bio", name: "bio", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "From", name: "from", widget: "date"}
      - {label: "To", name: "to", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Location" , name: "location", widget: "string"}
      - {label: "Website" , name: "website", widget: "string"}




  - name: "creative-board"
    label: "Creative Board"
    folder: "src/pages/board"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "action"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Category", name: "category", widget: "select", options: ["animation / animacija", "video / video", "blueprint / nacrt", "audio / audio", "design / dizajn", "photography / fotografija", "illustration / ilustracija", "toolkit / tulkit", "comic / strip", "publication / publikacija", "monster / monster", "infographic / infografika", "gif / gif", "booklet / buklet"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Members"
        name: "members"
        widget: "relations"
        limit: "300"
        collection: "members"
        searchFields: ["name"]
        valueField: "name"
      - label: "Actions"
        name: "actions"
        widget: "relations"
        limit: "300"
        collection: "actions"
        searchFields: ["name"]
      - label: "Projects"
        name: "projects"
        widget: "relations"
        limit: "300"
        collection: "projects"
        searchFields: ["name"]
      - {label: "Image", name: "image", widget: "image"}
      - label: "Item"
        name: "item"
        widget: "list"
        fields:
          - {label: "url", name: "url", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - label: "Event"
            name: "event"
            widget: "object"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Date", name: "date", widget: "date"}
              - {label: "Image", name: "image", widget: "image"}
          - label: "Featured Project"
            name: "featuredProject"
            widget: "relation"
            collection: "projects"
            searchFields: ["name"]
            valueField: "name"
            displayFields: ["title"]


      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Details", name: "details", widget: "markdown"}
          - label: "Documents"
            name: "documents"
            widget: "list"
            fields:
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
          - {label: "Presskit", name: "presskit", widget: "file"}