backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: assets/images

collections:
  - name: "actions"
    label: "Actions"
    folder: "src/pages/action"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "action"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Date from", name: "dateFrom", widget: "date"}
      - {label: "Date to", name: "dateFrom", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - label: "Featured Project"
            name: "featuredProject"
            widget: "relation"
            collection: "actions"
            searchFields: ["title"]
            valueField: "title"
            displayFields: ["twitterHandle"]

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Featured Action", name: "featuredAction", widget: "string"}
          - {label: "Details", name: "details", widget: "markdown"}